a=input('digite algo:')
print('o tipo primitivo é', type(a))
print('tem espaço?',a.isspace())
print('tem numero?',a.isnumeric())
print('tem so letras?',a.isalpha())
print('tem numero e letra?',a.isalnum())
print('Só tem letra maiuscula?',a.isupper())
print('só tem letra minuscula?',a.islower())
print('esta palavra esta capitalizada?',a.istitle())
